name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Her gün saat 00:00'da çalışır
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ertuyuksell
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
